'use client';

import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import {
  FiCompass,
  FiMap,
  FiStar,
  FiArrowRight,
  FiGlobe,
  FiShield,
  FiZap,
  FiMessageCircle,
  FiUsers,
  FiChevronDown,
} from 'react-icons/fi';
import DestinationCard from '@/components/destinations/DestinationCard';
import FAQ from '@/components/ui/FAQ';
import { authClient } from '@/lib/auth-client';
import api from '@/lib/api';

interface FeaturedDest {
  _id: string;
  name: string;
  country: string;
  continent: string;
  shortDescription: string;
  imageUrl: string;
  rating: number;
  reviewCount: number;
  categories: string[];
  averageCostPerDay: number;
  isFeatured: boolean;
}

const features = [
  {
    icon: FiZap,
    title: 'AI-Powered Planning',
    description: 'Get personalized day-by-day itineraries generated by advanced AI based on your preferences and budget.',
    gradient: 'from-blue-500 to-violet-600',
  },
  {
    icon: FiMessageCircle,
    title: 'Smart Travel Chat',
    description: 'Ask anything about your trip - visa info, packing tips, restaurant recommendations - and get instant answers.',
    gradient: 'from-emerald-500 to-teal-600',
  },
  {
    icon: FiStar,
    title: 'Personalized Recommendations',
    description: 'Discover destinations tailored to your interests, budget, and travel style with match scores.',
    gradient: 'from-amber-500 to-orange-600',
  },
  {
    icon: FiShield,
    title: 'Trip Management',
    description: 'Create, edit, and organize all your trips in one place with status tracking and itinerary storage.',
    gradient: 'from-pink-500 to-rose-600',
  },
];

const stats = [
  { icon: FiGlobe, value: '20+', label: 'Destinations' },
  { icon: FiUsers, value: '1K+', label: 'Travelers' },
  { icon: FiMap, value: '500+', label: 'Trips Planned' },
  { icon: FiStar, value: '4.9', label: 'AI Rating' },
];

const steps = [
  { num: '01', title: 'Choose Destination', description: 'Browse 20+ curated destinations or let AI recommend one for you.' },
  { num: '02', title: 'Set Preferences', description: 'Tell us your budget, travel style, interests, and trip duration.' },
  { num: '03', title: 'Get AI Itinerary', description: 'Receive a detailed day-by-day plan with costs, tips, and activities.' },
];

export default function HomePage() {
  const { data: session } = authClient.useSession();

  const { data: featuredData } = useQuery({
    queryKey: ['destinations', 'featured'],
    queryFn: async () => {
      const { data } = await api.get('/api/destinations', { params: { limit: 6, sort: 'rating-desc' } });
      return data.data;
    },
  });

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0">
          <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[60%] rounded-full bg-blue-500/10 blur-[120px]" />
          <div className="absolute bottom-[-20%] right-[-10%] w-[50%] h-[60%] rounded-full bg-violet-500/10 blur-[120px]" />
          <div className="absolute top-[20%] right-[20%] w-[30%] h-[40%] rounded-full bg-emerald-500/5 blur-[100px]" />
        </div>

        <div className="relative mx-auto max-w-7xl px-4 pt-20 pb-24 sm:px-6 sm:pt-28 sm:pb-32 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="text-center max-w-4xl mx-auto"
          >
            <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-500 to-violet-600 shadow-2xl shadow-blue-500/30">
              <FiCompass className="h-8 w-8 text-white" />
            </div>

            <h1 className="text-4xl font-extrabold tracking-tight text-zinc-900 dark:text-white sm:text-5xl lg:text-6xl xl:text-7xl">
              Travel Smarter with{' '}
              <span className="bg-gradient-to-r from-blue-400 via-violet-400 to-emerald-400 bg-clip-text text-transparent">
                AI-Powered
              </span>{' '}
              Planning
            </h1>

            <p className="mx-auto mt-6 max-w-2xl text-lg text-zinc-500 dark:text-zinc-400 sm:text-xl leading-relaxed">
              TripMind AI creates personalized travel itineraries, recommends hidden gems,
              and answers all your travel questions — all powered by advanced artificial intelligence.
            </p>

            <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                href={session?.user ? '/planner' : '/register'}
                className="inline-flex items-center gap-2.5 rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 px-8 py-3.5 text-sm font-semibold text-white shadow-2xl shadow-blue-500/25 hover:shadow-blue-500/40 hover:from-blue-500 hover:to-violet-500 active:scale-[0.98] transition-all"
              >
                <FiZap className="h-4 w-4" />
                Start Planning Free
                <FiArrowRight className="h-4 w-4" />
              </Link>
              <Link
                href="/explore"
                className="inline-flex items-center gap-2.5 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/60 px-8 py-3.5 text-sm font-semibold text-zinc-600 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-white hover:bg-zinc-100 dark:hover:bg-zinc-800/60 hover:border-zinc-300 dark:hover:border-zinc-700 backdrop-blur-sm transition-all"
              >
                <FiCompass className="h-4 w-4" />
                Explore Destinations
              </Link>
            </div>
          </motion.div>

          {/* Stats Row */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="mt-20 grid grid-cols-2 gap-4 sm:grid-cols-4 sm:gap-6 max-w-3xl mx-auto"
          >
            {stats.map((stat) => (
              <div key={stat.label} className="flex flex-col items-center gap-2 rounded-2xl border border-zinc-200 dark:border-zinc-800/60 bg-zinc-50 dark:bg-zinc-900/40 backdrop-blur-sm px-4 py-5">
                <stat.icon className="h-5 w-5 text-blue-500 dark:text-blue-400" />
                <span className="text-2xl font-bold text-zinc-900 dark:text-white">{stat.value}</span>
                <span className="text-xs text-zinc-500 font-medium">{stat.label}</span>
              </div>
            ))}
          </motion.div>

          {/* Scroll Down */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.8 }}
            className="mt-16 flex justify-center"
          >
            <button
              onClick={() => document.getElementById('how-it-works')?.scrollIntoView({ behavior: 'smooth' })}
              className="group flex flex-col items-center gap-2 text-zinc-400 dark:text-zinc-500 hover:text-zinc-600 dark:hover:text-zinc-300 transition-colors"
            >
              <span className="text-xs font-medium uppercase tracking-widest">Scroll to explore</span>
              <motion.div
                animate={{ y: [0, 6, 0] }}
                transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}
              >
                <FiChevronDown className="h-5 w-5" />
              </motion.div>
            </button>
          </motion.div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="relative border-t border-zinc-200 dark:border-zinc-800/60 bg-zinc-50 dark:bg-zinc-900/30">
        <div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-14"
          >
            <h2 className="text-3xl font-extrabold text-zinc-900 dark:text-white sm:text-4xl">
              How It <span className="bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent">Works</span>
            </h2>
            <p className="mt-3 text-zinc-500 dark:text-zinc-400 text-lg">Three simple steps to your perfect trip</p>
          </motion.div>

          <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
            {steps.map((step, i) => (
              <motion.div
                key={step.num}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.15 }}
                className="relative rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/60 p-8 text-center backdrop-blur-sm"
              >
                <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500/20 to-violet-500/20 border border-blue-500/20">
                  <span className="text-lg font-bold bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent">{step.num}</span>
                </div>
                <h3 className="text-lg font-bold text-zinc-900 dark:text-white mb-2">{step.title}</h3>
                <p className="text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed">{step.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="relative border-t border-zinc-200 dark:border-zinc-800/60">
        <div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-14"
          >
            <h2 className="text-3xl font-extrabold text-zinc-900 dark:text-white sm:text-4xl">
              Everything You Need to{' '}
              <span className="bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent">Travel Smarter</span>
            </h2>
            <p className="mt-3 text-zinc-500 dark:text-zinc-400 text-lg">Powerful AI tools to plan, manage, and enjoy your trips</p>
          </motion.div>

          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {features.map((feature, i) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="group rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/60 p-6 backdrop-blur-sm hover:border-zinc-300 dark:hover:border-zinc-700 hover:shadow-2xl hover:shadow-blue-500/5 transition-all duration-300"
              >
                <div className={`mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br ${feature.gradient} shadow-lg`}>
                  <feature.icon className="h-5 w-5 text-white" />
                </div>
                <h3 className="text-base font-bold text-zinc-900 dark:text-white mb-2">{feature.title}</h3>
                <p className="text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Featured Destinations */}
      {featuredData && featuredData.length > 0 && (
        <section className="relative border-t border-zinc-200 dark:border-zinc-800/60 bg-zinc-50 dark:bg-zinc-900/30">
          <div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
              className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-10 gap-4"
            >
              <div>
                <h2 className="text-3xl font-extrabold text-zinc-900 dark:text-white sm:text-4xl">
                  Popular <span className="bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent">Destinations</span>
                </h2>
                <p className="mt-2 text-zinc-500 dark:text-zinc-400">Top-rated places loved by travelers worldwide</p>
              </div>
              <Link
                href="/explore"
                className="inline-flex items-center gap-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/60 px-5 py-2.5 text-sm font-medium text-zinc-600 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-white hover:bg-zinc-100 dark:hover:bg-zinc-800/60 hover:border-zinc-300 dark:hover:border-zinc-700 transition-all self-start"
              >
                View All
                <FiArrowRight className="h-4 w-4" />
              </Link>
            </motion.div>

            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {featuredData.map((dest: FeaturedDest, i: number) => (
                <motion.div
                  key={dest._id}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: i * 0.08 }}
                >
                  <DestinationCard destination={dest} />
                </motion.div>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* FAQ Section */}
      <FAQ />

      {/* CTA Section */}
      <section className="relative border-t border-zinc-200 dark:border-zinc-800/60">
        <div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative overflow-hidden rounded-3xl border border-zinc-200 dark:border-zinc-800 bg-gradient-to-br from-zinc-50 dark:from-zinc-900 via-zinc-50 dark:via-zinc-900 to-blue-50 dark:to-blue-950/30 p-10 sm:p-14 text-center"
          >
            <div className="absolute top-[-20%] right-[-10%] w-[40%] h-[60%] rounded-full bg-blue-500/10 blur-[80px]" />
            <div className="absolute bottom-[-20%] left-[-10%] w-[40%] h-[60%] rounded-full bg-violet-500/10 blur-[80px]" />

            <div className="relative">
              <h2 className="text-3xl font-extrabold text-zinc-900 dark:text-white sm:text-4xl">
                Ready for Your Next Adventure?
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-zinc-500 dark:text-zinc-400 text-lg">
                Join TripMind AI and let artificial intelligence craft your perfect travel experience.
              </p>
              <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
                <Link
                  href={session?.user ? '/planner' : '/register'}
                  className="inline-flex items-center gap-2.5 rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 px-8 py-3.5 text-sm font-semibold text-white shadow-2xl shadow-blue-500/25 hover:shadow-blue-500/40 hover:from-blue-500 hover:to-violet-500 active:scale-[0.98] transition-all"
                >
                  Get Started for Free
                  <FiArrowRight className="h-4 w-4" />
                </Link>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
