import { MongoClient } from 'mongodb';
import dotenv from 'dotenv';
import path from 'path';
import { Destination } from '../models/Destination';

// Load env from server/.env
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const destinations: Omit<Destination, '_id'>[] = [
  {
    name: 'Paris',
    country: 'France',
    continent: 'Europe',
    description:
      'Paris, the City of Light, enchants visitors with its iconic landmarks, world-class museums, and romantic atmosphere. From the Eiffel Tower to the Louvre, every corner of Paris tells a story. Stroll along the Seine, savor croissants at a sidewalk café, and explore neighborhoods like Montmartre and Le Marais for an authentic Parisian experience.',
    shortDescription: 'The City of Light — iconic landmarks, art, and romance.',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800&q=80',
      'https://images.unsplash.com/photo-1549144511-f099e773c147?w=800&q=80',
      'https://images.unsplash.com/photo-1431274172761-fca41d930114?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 12450,
    categories: ['city', 'cultural'],
    bestTimeToVisit: 'April – June, September – November',
    averageCostPerDay: 150,
    currency: 'EUR',
    language: 'French',
    timezone: 'CET (UTC+1)',
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame Cathedral', 'Montmartre', 'Champs-Élysées'],
    coordinates: { lat: 48.8566, lng: 2.3522 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    description:
      'Tokyo is a dazzling megacity where ultra-modern skyscrapers stand beside ancient temples. Experience the world\'s freshest sushi at Tsukiji, wander the neon-lit streets of Shibuya, find serenity in Meiji Shrine, and immerse yourself in cutting-edge technology and pop culture in Akihabara.',
    shortDescription: 'A dazzling blend of tradition and cutting-edge modernity.',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=800&q=80',
      'https://images.unsplash.com/photo-1532236204992-f5e5fa5a9944?w=800&q=80',
      'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 15230,
    categories: ['city', 'cultural'],
    bestTimeToVisit: 'March – May, September – November',
    averageCostPerDay: 120,
    currency: 'JPY',
    language: 'Japanese',
    timezone: 'JST (UTC+9)',
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Meiji Shrine', 'Akihabara', 'Tsukiji Market'],
    coordinates: { lat: 35.6762, lng: 139.6503 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    description:
      'Bali is the Island of the Gods, a tropical paradise known for its lush rice terraces, volcanic mountains, pristine beaches, and vibrant Hindu culture. Whether you seek surfing in Uluwatu, yoga retreats in Ubud, or sunset cocktails in Seminyak, Bali offers an unforgettable escape.',
    shortDescription: 'Island of the Gods — rice terraces, beaches, and spirituality.',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80',
      'https://images.unsplash.com/photo-1573790387438-4da905039392?w=800&q=80',
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 9870,
    categories: ['beach', 'island', 'cultural', 'nature'],
    bestTimeToVisit: 'April – October',
    averageCostPerDay: 50,
    currency: 'IDR',
    language: 'Indonesian',
    timezone: 'WITA (UTC+8)',
    highlights: ['Tegallalang Rice Terraces', 'Uluwatu Temple', 'Ubud Monkey Forest', 'Seminyak Beach', 'Mount Batur'],
    coordinates: { lat: -8.3405, lng: 115.092 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'New York City',
    country: 'United States',
    continent: 'North America',
    description:
      'New York City, the Big Apple, is a global hub of culture, finance, and entertainment. From the Statue of Liberty to Central Park, Broadway shows to Brooklyn pizza, NYC offers an unparalleled urban adventure. Every borough has a distinct personality waiting to be explored.',
    shortDescription: 'The city that never sleeps — culture, cuisine, and energy.',
    imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80',
      'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800&q=80',
      'https://images.unsplash.com/photo-1522083165195-3424ed129620?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 18920,
    categories: ['city', 'cultural'],
    bestTimeToVisit: 'April – June, September – November',
    averageCostPerDay: 200,
    currency: 'USD',
    language: 'English',
    timezone: 'EST (UTC-5)',
    highlights: ['Statue of Liberty', 'Central Park', 'Times Square', 'Brooklyn Bridge', 'Metropolitan Museum'],
    coordinates: { lat: 40.7128, lng: -74.006 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Santorini',
    country: 'Greece',
    continent: 'Europe',
    description:
      'Santorini is a breathtaking volcanic island in the Aegean Sea, famous for its whitewashed buildings with blue domes, dramatic caldera views, stunning sunsets in Oia, and world-class wineries. Explore ancient ruins at Akrotiri and relax on unique red and black sand beaches.',
    shortDescription: 'Whitewashed cliffs, blue domes, and legendary sunsets.',
    imageUrl: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
      'https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=800&q=80',
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 8760,
    categories: ['island', 'beach', 'cultural'],
    bestTimeToVisit: 'April – October',
    averageCostPerDay: 130,
    currency: 'EUR',
    language: 'Greek',
    timezone: 'EET (UTC+2)',
    highlights: ['Oia Sunset', 'Caldera Views', 'Red Beach', 'Akrotiri Ruins', 'Santo Wines'],
    coordinates: { lat: 36.3932, lng: 25.4615 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cape Town',
    country: 'South Africa',
    continent: 'Africa',
    description:
      'Cape Town sits at the foot of Table Mountain, where the Atlantic and Indian Oceans converge. This stunning coastal city offers world-class vineyards, penguin colonies at Boulders Beach, the colorful Bo-Kaap neighborhood, and thrilling hikes on one of the New7Wonders of Nature.',
    shortDescription: 'Where mountains meet the ocean — vineyards, penguins, and adventure.',
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?w=800&q=80',
      'https://images.unsplash.com/photo-1591127233419-b73eb1e9ef16?w=800&q=80',
      'https://images.unsplash.com/photo-1552432027-64e66e301951?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 6540,
    categories: ['nature', 'adventure', 'beach', 'city'],
    bestTimeToVisit: 'November – March',
    averageCostPerDay: 80,
    currency: 'ZAR',
    language: 'English, Afrikaans, Xhosa',
    timezone: 'SAST (UTC+2)',
    highlights: ['Table Mountain', 'Cape of Good Hope', 'Boulders Beach Penguins', 'Bo-Kaap', 'Stellenbosch Vineyards'],
    coordinates: { lat: -33.9249, lng: 18.4241 },
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Machu Picchu',
    country: 'Peru',
    continent: 'South America',
    description:
      'Machu Picchu, the ancient Inca citadel perched high in the Andes Mountains, is one of the most awe-inspiring archaeological sites on Earth. Trek the Inca Trail through cloud forests, marvel at the precision of Incan stonework, and witness the sunrise over these mystical ruins at 2,430 meters above sea level.',
    shortDescription: 'The lost Inca citadel — ancient ruins high in the Andes.',
    imageUrl: 'https://images.unsplash.com/photo-1587595431973-160d0d163f34?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
      'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=800&q=80',
      'https://images.unsplash.com/photo-1548820778-992b8f90b97a?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 7320,
    categories: ['cultural', 'adventure', 'mountain'],
    bestTimeToVisit: 'May – September',
    averageCostPerDay: 70,
    currency: 'PEN',
    language: 'Spanish, Quechua',
    timezone: 'PET (UTC-5)',
    highlights: ['Inca Trail Trek', 'Sun Gate', 'Temple of the Sun', 'Huayna Picchu', 'Sacred Valley'],
    coordinates: { lat: -13.1631, lng: -72.545 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dubai',
    country: 'United Arab Emirates',
    continent: 'Asia',
    description:
      'Dubai is a futuristic metropolis rising from the desert, home to the world\'s tallest building, luxurious shopping malls, and man-made islands. Experience the thrill of desert safaris, ski indoors at Mall of the Emirates, and dine in underwater restaurants. A city that constantly redefines the impossible.',
    shortDescription: 'A futuristic desert oasis of luxury and superlatives.',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80',
      'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=800&q=80',
      'https://images.unsplash.com/photo-1526495124232-a04e1849168c?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 11230,
    categories: ['city', 'desert', 'adventure'],
    bestTimeToVisit: 'November – March',
    averageCostPerDay: 180,
    currency: 'AED',
    language: 'Arabic, English',
    timezone: 'GST (UTC+4)',
    highlights: ['Burj Khalifa', 'Palm Jumeirah', 'Dubai Mall', 'Desert Safari', 'Dubai Marina'],
    coordinates: { lat: 25.2048, lng: 55.2708 },
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Maldives',
    country: 'Maldives',
    continent: 'Asia',
    description:
      'The Maldives is the ultimate tropical paradise — a chain of 26 atolls in the Indian Ocean with crystal-clear turquoise waters, powdery white-sand beaches, and spectacular marine life. Stay in overwater bungalows, snorkel with manta rays, and watch bioluminescent plankton light up the shore at night.',
    shortDescription: 'Overwater villas and crystal-clear turquoise lagoons.',
    imageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80',
      'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=800&q=80',
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 5430,
    categories: ['island', 'beach', 'nature'],
    bestTimeToVisit: 'November – April',
    averageCostPerDay: 250,
    currency: 'MVR',
    language: 'Dhivehi',
    timezone: 'MVT (UTC+5)',
    highlights: ['Overwater Bungalows', 'Snorkeling with Manta Rays', 'Bioluminescent Beach', 'Male Atoll', 'Underwater Dining'],
    coordinates: { lat: 3.2028, lng: 73.2207 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Rome',
    country: 'Italy',
    continent: 'Europe',
    description:
      'Rome, the Eternal City, is a living museum spanning nearly 3,000 years of history. Walk through the Colosseum, toss a coin in the Trevi Fountain, marvel at the Sistine Chapel, and feast on authentic cacio e pepe in Trastevere. Every cobblestone street reveals another layer of history.',
    shortDescription: 'The Eternal City — ancient ruins, art, and la dolce vita.',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800&q=80',
      'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&q=80',
      'https://images.unsplash.com/photo-1525874684015-58379d421a52?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 14320,
    categories: ['city', 'cultural'],
    bestTimeToVisit: 'April – June, September – October',
    averageCostPerDay: 120,
    currency: 'EUR',
    language: 'Italian',
    timezone: 'CET (UTC+1)',
    highlights: ['Colosseum', 'Vatican Museums', 'Trevi Fountain', 'Pantheon', 'Trastevere'],
    coordinates: { lat: 41.9028, lng: 12.4964 },
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Barcelona',
    country: 'Spain',
    continent: 'Europe',
    description:
      'Barcelona is a vibrant Mediterranean city where Gaudí\'s surreal architecture meets golden beaches. Explore the whimsical Sagrada Família, stroll down La Rambla, savor tapas in the Gothic Quarter, and soak up the sun on Barceloneta Beach. A feast for the eyes and the palate.',
    shortDescription: 'Gaudí\'s masterpiece city — beaches, tapas, and art.',
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1562883676-8c7feb83f09b?w=800&q=80',
      'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&q=80',
      'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 11870,
    categories: ['city', 'beach', 'cultural'],
    bestTimeToVisit: 'May – June, September – October',
    averageCostPerDay: 110,
    currency: 'EUR',
    language: 'Spanish, Catalan',
    timezone: 'CET (UTC+1)',
    highlights: ['Sagrada Família', 'Park Güell', 'La Rambla', 'Gothic Quarter', 'Barceloneta Beach'],
    coordinates: { lat: 41.3874, lng: 2.1686 },
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Kyoto',
    country: 'Japan',
    continent: 'Asia',
    description:
      'Kyoto, Japan\'s ancient capital, is a serene city of over 2,000 temples, bamboo groves, and traditional geisha districts. Walk through the iconic Fushimi Inari gates, experience a tea ceremony, and witness cherry blossoms frame golden pavilions. Kyoto is where Japan\'s soul resides.',
    shortDescription: 'Ancient temples, bamboo groves, and timeless traditions.',
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
      'https://images.unsplash.com/photo-1504109586057-71a1c562d927?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 8930,
    categories: ['cultural', 'nature'],
    bestTimeToVisit: 'March – May, October – November',
    averageCostPerDay: 100,
    currency: 'JPY',
    language: 'Japanese',
    timezone: 'JST (UTC+9)',
    highlights: ['Fushimi Inari Shrine', 'Arashiyama Bamboo Grove', 'Kinkaku-ji', 'Gion District', 'Nishiki Market'],
    coordinates: { lat: 35.0116, lng: 135.7681 },
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Iceland',
    country: 'Iceland',
    continent: 'Europe',
    description:
      'Iceland is the land of fire and ice — a dramatic landscape of active volcanoes, massive glaciers, steaming geysers, and the ethereal Northern Lights. Drive the Ring Road, soak in the Blue Lagoon, hike behind waterfalls, and explore black-sand beaches at Vik for a truly otherworldly adventure.',
    shortDescription: 'Fire and ice — volcanoes, glaciers, and the Northern Lights.',
    imageUrl: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1520769945061-0a448c463865?w=800&q=80',
      'https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=800&q=80',
      'https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 5670,
    categories: ['nature', 'adventure'],
    bestTimeToVisit: 'June – August (summer), September – March (Northern Lights)',
    averageCostPerDay: 170,
    currency: 'ISK',
    language: 'Icelandic',
    timezone: 'GMT (UTC+0)',
    highlights: ['Northern Lights', 'Blue Lagoon', 'Golden Circle', 'Jökulsárlón Glacier Lagoon', 'Seljalandsfoss Waterfall'],
    coordinates: { lat: 64.9631, lng: -19.0208 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Marrakech',
    country: 'Morocco',
    continent: 'Africa',
    description:
      'Marrakech is a sensory explosion — a vibrant maze of souks, spice-scented alleyways, and ornate palaces. Lose yourself in the Jemaa el-Fna square at dusk, admire the intricate tilework of Ben Youssef Madrasa, and retreat to a tranquil riad after a day of haggling in the medina.',
    shortDescription: 'A sensory explosion of souks, spices, and ancient palaces.',
    imageUrl: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800&q=80',
      'https://images.unsplash.com/photo-1560095633-0a35f81f2eb2?w=800&q=80',
      'https://images.unsplash.com/photo-1585133064784-3b50c2c2b862?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 7120,
    categories: ['cultural', 'city', 'desert'],
    bestTimeToVisit: 'March – May, September – November',
    averageCostPerDay: 55,
    currency: 'MAD',
    language: 'Arabic, French, Berber',
    timezone: 'WET (UTC+1)',
    highlights: ['Jemaa el-Fna', 'Majorelle Garden', 'Bahia Palace', 'Medina Souks', 'Atlas Mountains Day Trip'],
    coordinates: { lat: 31.6295, lng: -7.9811 },
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Queenstown',
    country: 'New Zealand',
    continent: 'Oceania',
    description:
      'Queenstown is the adventure capital of the world, nestled on the shores of Lake Wakatipu surrounded by the Remarkables mountain range. Bungee jump, skydive, jet boat, ski, or simply cruise Milford Sound. Every season offers a different kind of breathtaking beauty.',
    shortDescription: 'Adventure capital of the world — mountains, lakes, and thrills.',
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80',
      'https://images.unsplash.com/photo-1469521669194-babb45599def?w=800&q=80',
      'https://images.unsplash.com/photo-1455276097693-01ec6e65d16c?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 4980,
    categories: ['adventure', 'mountain', 'nature'],
    bestTimeToVisit: 'December – February (summer), June – August (skiing)',
    averageCostPerDay: 140,
    currency: 'NZD',
    language: 'English',
    timezone: 'NZST (UTC+12)',
    highlights: ['Milford Sound', 'Bungee Jumping', 'Remarkables Ski Area', 'Lake Wakatipu', 'Skyline Gondola'],
    coordinates: { lat: -45.0312, lng: 168.6626 },
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Rio de Janeiro',
    country: 'Brazil',
    continent: 'South America',
    description:
      'Rio de Janeiro is a vibrant coastal city framed by granite peaks and golden beaches. Dance the samba at Carnival, ride the cable car to Sugarloaf Mountain, watch the sunset from Ipanema, and stand at the feet of Christ the Redeemer overlooking one of the world\'s most beautiful cities.',
    shortDescription: 'Samba, sunsets, and Sugarloaf — Brazil\'s marvelous city.',
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=800&q=80',
      'https://images.unsplash.com/photo-1544989164-31dc3291c654?w=800&q=80',
      'https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 8450,
    categories: ['beach', 'city', 'cultural', 'adventure'],
    bestTimeToVisit: 'December – March',
    averageCostPerDay: 75,
    currency: 'BRL',
    language: 'Portuguese',
    timezone: 'BRT (UTC-3)',
    highlights: ['Christ the Redeemer', 'Sugarloaf Mountain', 'Copacabana Beach', 'Carnival', 'Tijuca Forest'],
    coordinates: { lat: -22.9068, lng: -43.1729 },
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Petra',
    country: 'Jordan',
    continent: 'Asia',
    description:
      'Petra, the Rose City, is an ancient Nabataean city carved entirely into pink sandstone cliffs. Walk through the narrow Siq canyon to reveal the iconic Treasury, explore royal tombs, and climb to the Monastery for panoramic desert views. One of the New Seven Wonders of the World.',
    shortDescription: 'The Rose City — ancient wonder carved into sandstone cliffs.',
    imageUrl: 'https://images.unsplash.com/photo-1579606032821-4e6161c81571?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1563804951831-7d7e0081c2e0?w=800&q=80',
      'https://images.unsplash.com/photo-1580834341580-8c17a3a630ca?w=800&q=80',
      'https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 6230,
    categories: ['cultural', 'adventure', 'desert'],
    bestTimeToVisit: 'March – May, September – November',
    averageCostPerDay: 65,
    currency: 'JOD',
    language: 'Arabic',
    timezone: 'EET (UTC+2)',
    highlights: ['The Treasury', 'The Siq', 'The Monastery', 'Royal Tombs', 'Petra by Night'],
    coordinates: { lat: 30.3285, lng: 35.4444 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Havana',
    country: 'Cuba',
    continent: 'North America',
    description:
      'Havana is a time capsule of colorful colonial architecture, classic 1950s American cars, and intoxicating live salsa music. Walk along the Malecón waterfront, sip mojitos at La Bodeguita del Medio, and explore the art-filled streets of Old Havana, a UNESCO World Heritage Site.',
    shortDescription: 'Vintage cars, salsa rhythms, and colorful colonial charm.',
    imageUrl: 'https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1570299437522-25b739d1ae01?w=800&q=80',
      'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800&q=80',
      'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80',
    ],
    rating: 4.4,
    reviewCount: 4560,
    categories: ['cultural', 'city', 'beach'],
    bestTimeToVisit: 'November – April',
    averageCostPerDay: 45,
    currency: 'CUP',
    language: 'Spanish',
    timezone: 'CST (UTC-5)',
    highlights: ['Old Havana', 'Malecón', 'Capitol Building', 'Vintage Car Tours', 'Plaza Vieja'],
    coordinates: { lat: 23.1136, lng: -82.3666 },
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Banff',
    country: 'Canada',
    continent: 'North America',
    description:
      'Banff National Park is Canada\'s crown jewel — a pristine wilderness of turquoise glacial lakes, towering Rocky Mountain peaks, and abundant wildlife. Canoe on Lake Louise, hike to Moraine Lake, soak in Banff Upper Hot Springs, and spot grizzly bears in one of the most photogenic landscapes on Earth.',
    shortDescription: 'Turquoise lakes and towering Rockies in Canada\'s wilderness.',
    imageUrl: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=800&q=80',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
      'https://images.unsplash.com/photo-1609825488888-3a766db05542?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 7650,
    categories: ['nature', 'mountain', 'adventure'],
    bestTimeToVisit: 'June – August (summer), December – March (skiing)',
    averageCostPerDay: 130,
    currency: 'CAD',
    language: 'English, French',
    timezone: 'MST (UTC-7)',
    highlights: ['Lake Louise', 'Moraine Lake', 'Banff Gondola', 'Icefields Parkway', 'Johnston Canyon'],
    coordinates: { lat: 51.4968, lng: -115.9281 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Swiss Alps',
    country: 'Switzerland',
    continent: 'Europe',
    description:
      'The Swiss Alps are the epitome of alpine grandeur — snow-capped peaks, charming mountain villages, world-class skiing, and scenic train rides. Take the Glacier Express, paraglide over Interlaken, hike the Eiger Trail, and enjoy fondue with panoramic views of the Matterhorn.',
    shortDescription: 'Alpine grandeur — peaks, chalets, and scenic train journeys.',
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=800&q=80',
      'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80',
      'https://images.unsplash.com/photo-1491555103944-7c647fd857e6?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 9320,
    categories: ['mountain', 'nature', 'adventure'],
    bestTimeToVisit: 'June – September (hiking), December – March (skiing)',
    averageCostPerDay: 200,
    currency: 'CHF',
    language: 'German, French, Italian',
    timezone: 'CET (UTC+1)',
    highlights: ['Matterhorn', 'Jungfraujoch', 'Glacier Express', 'Interlaken', 'Lake Geneva'],
    coordinates: { lat: 46.8182, lng: 8.2275 },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

async function seed() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('❌  MONGODB_URI is not defined in server/.env');
    process.exit(1);
  }

  const client = new MongoClient(uri);

  try {
    await client.connect();
    const dbName = uri.split('/').pop()?.split('?')[0] || 'tripmind-ai';
    const db = client.db(dbName);
    const collection = db.collection('destinations');

    // Drop existing destinations
    await collection.deleteMany({});
    console.log('🗑️  Cleared existing destinations');

    // Insert seed data
    const result = await collection.insertMany(destinations);
    console.log(`✅  Seeded ${result.insertedCount} destinations successfully!`);

    // Create indexes for search performance
    await collection.createIndex(
      { name: 'text', country: 'text', description: 'text' },
      { default_language: 'none', language_override: 'textSearchLanguage' }
    );
    await collection.createIndex({ continent: 1 });
    await collection.createIndex({ categories: 1 });
    await collection.createIndex({ rating: -1 });
    await collection.createIndex({ averageCostPerDay: 1 });
    console.log('📇  Created database indexes');
  } catch (error) {
    console.error('❌  Seed failed:', error);
    process.exit(1);
  } finally {
    await client.close();
    console.log('👋  Database connection closed');
  }
}

seed();
